### ISSUE TITLE
Hi, I am using Netlify with parallel image processing plugin

### ISSUE THREAD

**Issue by daiky00** [netlify/gatsby-parallel-runner#18]
Hi,
I am using Netlify with parallel image processing plugin. But the build is slow can you help me improve it or take a look at it..... the repo is private though so I will need to give you access. I am also using Netlify incremental build which is great but my problem is with the first build. Also Netlify has cap of build time of 15 minutes and I contact Netlify to increase it to 1 hour

**Comment by jlengstorf** [comment]
hey, @daiky00!

the best place for questions like this is https://community.netlify.com — there's an active community there

I've written up a few things to check that might speed up your builds here: https://www.netlify.com/blog/2020/06/11/5-optimizations-for-faster-gatsby-builds/

good luck!
